apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/nginx-test-website:latest
        ports:
        - containerPort: 80